apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: back
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ghcr.io/richardvanraes/mlops-examen-backend:latest
        ports:
        - containerPort: 8080