apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: front
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ghcr.io/richardvanraes/mlops-examen-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: name
        - name: DATE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: date