apiVersion: v1
kind: Service
metadata:
  name: api-service-back
  namespace: exam-richardvanraes
spec:
  selector:
    app: back
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort