apiVersion: v1
kind: Service
metadata:
  name: api-service-front
  namespace: exam-richardvanraes
spec:
  selector:
    app: front
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
