services:
  api:
    image: api-exam
    build:
      context: api
      dockerfile: dockerfile
    environment:
      file_format: json
  frontend:
    image: frontend-exam
    build:
      context: frontend
      dockerfile: frontend-dockerfile
    environment:
      API_HOST: api
      API_PORT: 8080
