services:
  api:
    image: richardvanraes/mlops-exam-backend
    build:
      context: api
      dockerfile: dockerfile
    environment:
      file_format: json
    ports:
      - "8080:8080"
  frontend:
    image: richardvanraes/mlops-exam-frontend
    build:
      context: frontend
      dockerfile: frontend-dockerfile
    environment:
      API_HOST: api
      API_PORT: 8080
    ports:
      - "8001:80"